name: ⭐ Update Catalog

on:
  schedule:
    - cron: '0 3 * * *'  # Выполняется ежедневно в 3 часа утра UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build catalog
        run: npm run build:catalog

      - name: Check for changes in catalog.json
        id: check-changes
        shell: bash
        run: |
          if [[ $(git diff --stat src/assets/catalog.json | wc -l) != 0 ]]; then
              echo "has_changes=true" >> $GITHUB_OUTPUT
          else
              echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add src/assets/catalog.json
          git commit -m "Update catalog.json"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main
